# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profiles_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
