# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
