# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 17:17
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('pt', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
