# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20160728_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='my location', max_length=100),
        ),
    ]
